Remove rxjava2 from Micronaut 5.0.0 BOM
micronaut-projects/micronaut-platform pull request #1427
Opened 2024-04-18 14:36 UTC by timyates

Closes #1424

2024-04-18 18:38 UTC, sdelamo approved these changes

2024-04-18 18:39 UTC, sdelamo requested changes
@timyates Create a breaking changes section in the Micronaut Platform documentation and document this change.

2024-04-19 14:26 UTC, timyates commented
@sdelamo done 👍

2024-04-22 05:02 UTC, sdelamo approved these changes

2024-04-22 05:03 UTC, merged